global:
  domain: argocd.local

configs:
  params:
    server.insecure: true

server:
  service:
    type: LoadBalancer

redis:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
